### ISSUE TITLE
componentWillReceiveProps not using nextProps

### ISSUE THREAD

**Issue by mamoschli** [Jackong/redux-authentication#1]
Hi,
maybe this isn't a bug and works as designed but I think the behavior of `componentWillReceiveProps()` in your library is not correct.

I understand that when changing the `isAuthenticated` prop the `AuthComponent`should automatically redirect (or not) based on the value. But when I dispatch a Redux action that changes `isAuthenticated` in my store to `false` the `componentWillReceiveProps()` function checks the current props where the value is still `true`.

I try to open a Pull request for this.

**Comment by Jackong** [comment]
thank you~
